language: go
go: "1.11.x"

cache:
  directories:
  - $GOPATH/pkg

env:
  global:
  - GO111MODULE=on
  - GOARCH=amd64
  - PROTOC_VER="3.6.1"
  matrix:
  - GOOS=linux
  - GOOS=darwin
  - GOOS=windows

before_install:
- curl -o /tmp/protoc.zip -sL "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip"
- unzip /tmp/protoc.zip -d /tmp
- sudo mv /tmp/bin/protoc /usr/local/bin/protoc
- sudo mv /tmp/include/google /usr/local/include/google

script:
- make -B clean test build
- gofmt -w -s $(go list -f '{{ .Dir }}' ./...)
- git diff --exit-code
