language: go
go:
- "1.11"
cache:
  directories:
  - $GOPATH/pkg
install: true

jobs:
  include:
  - stage: test
    env: GO111MODULE=on
    script: make test
  - stage: build
    env: GO111MODULE=on GOOS=linux GOARCH=amd64
    script: make build
  - stage: build
    env: GO111MODULE=on GOOS=darwin GOARCH=amd64
    script: make build
  - stage: build
    env: GO111MODULE=on GOOS=windows GOARCH=amd64
    script: make build
