language: go
go:
  - "1.11"

cache:
  directories:
    - $GOPATH/pkg

install:
  - curl https://raw.githubusercontent.com/golang/dep/v0.5.0/install.sh | sh

jobs:
  include:
    - stage: test
      env: GO111MODULE=on
      script: make test

    - stage: build
      env: GO111MODULE=on GOOS=linux GOARCH=amd64
      script: make -B build

    - stage: build
      env: GO111MODULE=on GOOS=darwin GOARCH=amd64
      script: make -B build

    - stage: build
      env: GO111MODULE=on GOOS=windows GOARCH=amd64
      script: make -B build
