required = ["github.com/gogo/protobuf/gogoproto"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/pseudomuto/protokit"
