// Copyright © 2019 The Things Network Foundation, The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"github.com/TheThingsIndustries/protoc-gen-fieldmask/module"
	"github.com/TheThingsIndustries/protoc-gen-fieldmask/processor"
	pgs "github.com/lyft/protoc-gen-star"
	pgsgo "github.com/lyft/protoc-gen-star/lang/go"
	pgvmodule "github.com/lyft/protoc-gen-validate/module"
)

const FileHeader = `// Code generated by protoc-gen-fieldmask. DO NOT EDIT.`

var initGoContext = pgsgo.InitGoGoContext

func main() {
	pgs.Init(
		pgs.DebugEnv("DEBUG"),
	).RegisterModule(
		module.Pather(initGoContext),
		module.Setter(initGoContext),
		pgvmodule.Validator(),
	).RegisterPostProcessor(
		processor.HeaderPrepender(FileHeader),
		pgsgo.GoFmt(),
	).Render()
}
