// Copyright © 2024 The Things Industries
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: thethings/rpcmask/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Generate field mask for the following RPC method.
	MethodName string `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// The generated field mask.
	FieldMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Generate the set field for the RPC method.
	Set bool `protobuf:"varint,3,opt,name=set,proto3" json:"set,omitempty"`
}

func (x *RPCMask) Reset() {
	*x = RPCMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thethings_rpcmask_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMask) ProtoMessage() {}

func (x *RPCMask) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_rpcmask_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMask.ProtoReflect.Descriptor instead.
func (*RPCMask) Descriptor() ([]byte, []int) {
	return file_thethings_rpcmask_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *RPCMask) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *RPCMask) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *RPCMask) GetSet() bool {
	if x != nil {
		return x.Set
	}
	return false
}

type MessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// RPCMask options for this message.
	Rpcmasks []*RPCMask `protobuf:"bytes,1,rep,name=rpcmasks,proto3" json:"rpcmasks,omitempty"`
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thethings_rpcmask_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_rpcmask_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_thethings_rpcmask_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetRpcmasks() []*RPCMask {
	if x != nil {
		return x.Rpcmasks
	}
	return nil
}

var file_thethings_rpcmask_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         52803,
		Name:          "thethings.rpcmask.message",
		Tag:           "bytes,52803,opt,name=message",
		Filename:      "thethings/rpcmask/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional thethings.rpcmask.MessageOptions message = 52803;
	E_Message = &file_thethings_rpcmask_annotations_proto_extTypes[0]
)

var File_thethings_rpcmask_annotations_proto protoreflect.FileDescriptor

var file_thethings_rpcmask_annotations_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x68, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x6d,
	0x61, 0x73, 0x6b, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x74, 0x68, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x72, 0x70, 0x63, 0x6d, 0x61, 0x73, 0x6b, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x07,
	0x52, 0x50, 0x43, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d,
	0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x73, 0x65, 0x74, 0x22, 0x48, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x70, 0x63, 0x6d, 0x61,
	0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x68, 0x65, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x72, 0x70, 0x63, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x50,
	0x43, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x08, 0x72, 0x70, 0x63, 0x6d, 0x61, 0x73, 0x6b, 0x73, 0x3a,
	0x5e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xc3, 0x9c, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x68, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2e,
	0x72, 0x70, 0x63, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68,
	0x65, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thethings_rpcmask_annotations_proto_rawDescOnce sync.Once
	file_thethings_rpcmask_annotations_proto_rawDescData = file_thethings_rpcmask_annotations_proto_rawDesc
)

func file_thethings_rpcmask_annotations_proto_rawDescGZIP() []byte {
	file_thethings_rpcmask_annotations_proto_rawDescOnce.Do(func() {
		file_thethings_rpcmask_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_thethings_rpcmask_annotations_proto_rawDescData)
	})
	return file_thethings_rpcmask_annotations_proto_rawDescData
}

var file_thethings_rpcmask_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thethings_rpcmask_annotations_proto_goTypes = []interface{}{
	(*RPCMask)(nil),                     // 0: thethings.rpcmask.RPCMask
	(*MessageOptions)(nil),              // 1: thethings.rpcmask.MessageOptions
	(*fieldmaskpb.FieldMask)(nil),       // 2: google.protobuf.FieldMask
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_thethings_rpcmask_annotations_proto_depIdxs = []int32{
	2, // 0: thethings.rpcmask.RPCMask.field_mask:type_name -> google.protobuf.FieldMask
	0, // 1: thethings.rpcmask.MessageOptions.rpcmasks:type_name -> thethings.rpcmask.RPCMask
	3, // 2: thethings.rpcmask.message:extendee -> google.protobuf.MessageOptions
	1, // 3: thethings.rpcmask.message:type_name -> thethings.rpcmask.MessageOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_thethings_rpcmask_annotations_proto_init() }
func file_thethings_rpcmask_annotations_proto_init() {
	if File_thethings_rpcmask_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thethings_rpcmask_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thethings_rpcmask_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thethings_rpcmask_annotations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_thethings_rpcmask_annotations_proto_goTypes,
		DependencyIndexes: file_thethings_rpcmask_annotations_proto_depIdxs,
		MessageInfos:      file_thethings_rpcmask_annotations_proto_msgTypes,
		ExtensionInfos:    file_thethings_rpcmask_annotations_proto_extTypes,
	}.Build()
	File_thethings_rpcmask_annotations_proto = out.File
	file_thethings_rpcmask_annotations_proto_rawDesc = nil
	file_thethings_rpcmask_annotations_proto_goTypes = nil
	file_thethings_rpcmask_annotations_proto_depIdxs = nil
}
