// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package otherpackage

type RPCFieldMaskPathValue struct {
	All     []string
	Allowed []string
	Set     bool
}

// RPCFieldMaskPaths lists the field mask paths for each RPC in this API.
var RPCFieldMaskPaths = map[string]RPCFieldMaskPathValue{}
