// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: otherpackage/otherpackage.proto

package otherpackage

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Embed struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Embed) Reset()         { *m = Embed{} }
func (m *Embed) String() string { return proto.CompactTextString(m) }
func (*Embed) ProtoMessage()    {}
func (*Embed) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ead452a5991fdb1, []int{0}
}
func (m *Embed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Embed.Unmarshal(m, b)
}
func (m *Embed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Embed.Marshal(b, m, deterministic)
}
func (m *Embed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Embed.Merge(m, src)
}
func (m *Embed) XXX_Size() int {
	return xxx_messageInfo_Embed.Size(m)
}
func (m *Embed) XXX_DiscardUnknown() {
	xxx_messageInfo_Embed.DiscardUnknown(m)
}

var xxx_messageInfo_Embed proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Embed)(nil), "otherpackage.Embed")
}

func init() { proto.RegisterFile("otherpackage/otherpackage.proto", fileDescriptor_9ead452a5991fdb1) }

var fileDescriptor_9ead452a5991fdb1 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x2f, 0xc9, 0x48,
	0x2d, 0x2a, 0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0xd5, 0x47, 0xe6, 0xe8, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0xf1, 0x20, 0x8b, 0x29, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x26, 0xa5, 0xa6, 0x38, 0x79,
	0x47, 0x79, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x87, 0x64, 0xa4,
	0x86, 0x64, 0x64, 0xe6, 0xa5, 0x17, 0x7b, 0xe6, 0xa5, 0x94, 0x16, 0x97, 0x14, 0x65, 0xa6, 0x16,
	0xeb, 0x83, 0xb5, 0x27, 0xeb, 0xa6, 0xa7, 0xe6, 0xe9, 0xa6, 0x65, 0xa6, 0xe6, 0xa4, 0xe4, 0x26,
	0x16, 0x67, 0xeb, 0x97, 0xa4, 0x16, 0x97, 0xa4, 0x24, 0x96, 0x24, 0xa2, 0xd8, 0x94, 0xc4, 0x06,
	0x56, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x53, 0x3a, 0x5c, 0x34, 0x8d, 0x00, 0x00, 0x00,
}
