// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// ValidateFields checks the field values on Foo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Foo) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = FooFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "id":
			// no validation rules for Id
		case "a":
			// no validation rules for A
		case "nested":

			if v, ok := interface{}(m.GetNested()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return FooValidationError{
						field:  "nested",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "duration":

			if v, ok := interface{}(m.GetDuration()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return FooValidationError{
						field:  "duration",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "created_at":

			if v, ok := interface{}(m.GetCreatedAt()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return FooValidationError{
						field:  "created_at",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "bars":

			for idx, item := range m.GetBars() {
				_, _ = idx, item

				if v, ok := interface{}(item).(interface{ ValidateFields(...string) error }); ok {
					if err := v.ValidateFields(subs...); err != nil {
						return FooValidationError{
							field:  fmt.Sprintf("bars[%v]", idx),
							reason: "embedded message failed validation",
							cause:  err,
						}
					}
				}

			}

		case "foo_oneof":
			if len(subs) == 0 {
				subs = []string{
					"d", "e", "f",
				}
			}
			for name, subs := range _processPaths(subs) {
				_ = subs
				switch name {
				case "d":
					w, ok := m.FooOneof.(*Foo_D)
					if !ok || w == nil {
						continue
					}
					// no validation rules for D
				case "e":
					w, ok := m.FooOneof.(*Foo_E)
					if !ok || w == nil {
						continue
					}
					// no validation rules for E
				case "f":
					w, ok := m.FooOneof.(*Foo_F)
					if !ok || w == nil {
						continue
					}
					// no validation rules for F
				}
			}
		default:
			return FooValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// FooValidationError is the validation error returned by Foo.ValidateFields if
// the designated constraints aren't met.
type FooValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FooValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FooValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FooValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FooValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FooValidationError) ErrorName() string { return "FooValidationError" }

// Error satisfies the builtin error interface
func (e FooValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FooValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FooValidationError{}

// ValidateFields checks the field values on Bar with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Bar) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = BarFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "id":
			// no validation rules for Id
		case "g":
			// no validation rules for G
		case "created_at":

			if v, ok := interface{}(m.GetCreatedAt()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return BarValidationError{
						field:  "created_at",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return BarValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// BarValidationError is the validation error returned by Bar.ValidateFields if
// the designated constraints aren't met.
type BarValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BarValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BarValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BarValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BarValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BarValidationError) ErrorName() string { return "BarValidationError" }

// Error satisfies the builtin error interface
func (e BarValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBar.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BarValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BarValidationError{}

// ValidateFields checks the field values on ListFooResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListFooResponse) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = ListFooResponseFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "foos":

			for idx, item := range m.GetFoos() {
				_, _ = idx, item

				if v, ok := interface{}(item).(interface{ ValidateFields(...string) error }); ok {
					if err := v.ValidateFields(subs...); err != nil {
						return ListFooResponseValidationError{
							field:  fmt.Sprintf("foos[%v]", idx),
							reason: "embedded message failed validation",
							cause:  err,
						}
					}
				}

			}

		default:
			return ListFooResponseValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// ListFooResponseValidationError is the validation error returned by
// ListFooResponse.ValidateFields if the designated constraints aren't met.
type ListFooResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFooResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFooResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFooResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFooResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFooResponseValidationError) ErrorName() string { return "ListFooResponseValidationError" }

// Error satisfies the builtin error interface
func (e ListFooResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFooResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFooResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFooResponseValidationError{}

// ValidateFields checks the field values on Foo_FooNested with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *Foo_FooNested) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = Foo_FooNestedFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "id":
			// no validation rules for Id
		case "b":
			// no validation rules for B
		case "mappings":

			for key, val := range m.GetMappings() {
				_ = val

				// no validation rules for Mappings[key]

				if v, ok := interface{}(val).(interface{ ValidateFields(...string) error }); ok {
					if err := v.ValidateFields(subs...); err != nil {
						return Foo_FooNestedValidationError{
							field:  fmt.Sprintf("mappings[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						}
					}
				}

			}

		case "nested_nested":

			if v, ok := interface{}(m.GetNestedNested()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return Foo_FooNestedValidationError{
						field:  "nested_nested",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return Foo_FooNestedValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// Foo_FooNestedValidationError is the validation error returned by
// Foo_FooNested.ValidateFields if the designated constraints aren't met.
type Foo_FooNestedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Foo_FooNestedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Foo_FooNestedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Foo_FooNestedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Foo_FooNestedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Foo_FooNestedValidationError) ErrorName() string { return "Foo_FooNestedValidationError" }

// Error satisfies the builtin error interface
func (e Foo_FooNestedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoo_FooNested.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Foo_FooNestedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Foo_FooNestedValidationError{}

// ValidateFields checks the field values on Foo_FooNested_FooNestedNested with
// the rules defined in the proto definition for this message. If any rules
// are violated, an error is returned.
func (m *Foo_FooNested_FooNestedNested) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = Foo_FooNested_FooNestedNestedFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "id":
			// no validation rules for Id
		case "c":
			// no validation rules for C
		case "data":
			// no validation rules for Data
		default:
			return Foo_FooNested_FooNestedNestedValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// Foo_FooNested_FooNestedNestedValidationError is the validation error
// returned by Foo_FooNested_FooNestedNested.ValidateFields if the designated
// constraints aren't met.
type Foo_FooNested_FooNestedNestedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Foo_FooNested_FooNestedNestedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Foo_FooNested_FooNestedNestedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Foo_FooNested_FooNestedNestedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Foo_FooNested_FooNestedNestedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Foo_FooNested_FooNestedNestedValidationError) ErrorName() string {
	return "Foo_FooNested_FooNestedNestedValidationError"
}

// Error satisfies the builtin error interface
func (e Foo_FooNested_FooNestedNestedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoo_FooNested_FooNestedNested.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Foo_FooNested_FooNestedNestedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Foo_FooNested_FooNestedNestedValidationError{}
