// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

var BarFieldPathsNested = []string{
	"created_at",
	"g",
	"id",
}

var BarFieldPathsTopLevel = []string{
	"created_at",
	"g",
	"id",
}

var FooFieldPathsNested = []string{
	"a",
	"bars",
	"created_at",
	"duration",
	"foo_oneof",
	"foo_oneof.d",
	"foo_oneof.e",
	"foo_oneof.f",
	"id",
	"nested",
	"nested.b",
	"nested.id",
	"nested.mappings",
	"nested.nested_nested",
	"nested.nested_nested.c",
	"nested.nested_nested.data",
	"nested.nested_nested.id",
}

var FooFieldPathsTopLevel = []string{
	"a",
	"bars",
	"created_at",
	"duration",
	"foo_oneof",
	"id",
	"nested",
}

var Foo_FooNestedFieldPathsNested = []string{
	"b",
	"id",
	"mappings",
	"nested_nested",
	"nested_nested.c",
	"nested_nested.data",
	"nested_nested.id",
}

var Foo_FooNestedFieldPathsTopLevel = []string{
	"b",
	"id",
	"mappings",
	"nested_nested",
}

var Foo_FooNested_FooNestedNestedFieldPathsNested = []string{
	"c",
	"data",
	"id",
}

var Foo_FooNested_FooNestedNestedFieldPathsTopLevel = []string{
	"c",
	"data",
	"id",
}

var ListFooResponseFieldPathsNested = []string{
	"foos",
}

var ListFooResponseFieldPathsTopLevel = []string{
	"foos",
}
