// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

import fmt "fmt"

func (dst *Foo) SetFields(src *Foo, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "id":
			if len(subs) > 0 {
				return fmt.Errorf("'id' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Id = src.Id
			} else {
				var zero string
				dst.Id = zero
			}
		case "a":
			if len(subs) > 0 {
				return fmt.Errorf("'a' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.A = src.A
			} else {
				var zero int32
				dst.A = zero
			}
		case "nested":
			if len(subs) > 0 {
				var newDst, newSrc *Foo_FooNested
				if (src == nil || src.Nested == nil) && dst.Nested == nil {
					continue
				}
				if src != nil {
					newSrc = src.Nested
				}
				if dst.Nested != nil {
					newDst = dst.Nested
				} else {
					newDst = &Foo_FooNested{}
					dst.Nested = newDst
				}
				if err := newDst.SetFields(newSrc, subs...); err != nil {
					return err
				}
			} else {
				if src != nil {
					dst.Nested = src.Nested
				} else {
					dst.Nested = nil
				}
			}
		case "duration":
			if len(subs) > 0 {
				return fmt.Errorf("'duration' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Duration = src.Duration
			} else {
				dst.Duration = nil
			}
		case "created_at":
			if len(subs) > 0 {
				return fmt.Errorf("'created_at' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.CreatedAt = src.CreatedAt
			} else {
				dst.CreatedAt = nil
			}
		case "bars":
			if len(subs) > 0 {
				return fmt.Errorf("'bars' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Bars = src.Bars
			} else {
				dst.Bars = nil
			}

		case "foo_oneof":
			if len(subs) == 0 && src == nil {
				dst.FooOneof = nil
				continue
			} else if len(subs) == 0 {
				dst.FooOneof = src.FooOneof
				continue
			}

			subPathMap := _processPaths(subs)
			if len(subPathMap) > 1 {
				return fmt.Errorf("more than one field specified for oneof field '%s'", name)
			}
			for oneofName, oneofSubs := range subPathMap {
				switch oneofName {
				case "d":
					var srcTypeOk bool
					if src != nil {
						_, srcTypeOk = src.FooOneof.(*Foo_D)
					}
					if srcValid := srcTypeOk || src == nil || src.FooOneof == nil || len(oneofSubs) == 0; !srcValid {
						return fmt.Errorf("attempt to set oneof 'd', while different oneof is set in source")
					}
					_, dstTypeOk := dst.FooOneof.(*Foo_D)
					if dstValid := dstTypeOk || dst.FooOneof == nil || len(oneofSubs) == 0; !dstValid {
						return fmt.Errorf("attempt to set oneof 'd', while different oneof is set in destination")
					}
					if len(oneofSubs) > 0 {
						return fmt.Errorf("'d' has no subfields, but %s were specified", oneofSubs)
					}
					if srcTypeOk {
						dst.FooOneof = src.FooOneof
					} else {
						dst.FooOneof = nil
					}
				case "e":
					var srcTypeOk bool
					if src != nil {
						_, srcTypeOk = src.FooOneof.(*Foo_E)
					}
					if srcValid := srcTypeOk || src == nil || src.FooOneof == nil || len(oneofSubs) == 0; !srcValid {
						return fmt.Errorf("attempt to set oneof 'e', while different oneof is set in source")
					}
					_, dstTypeOk := dst.FooOneof.(*Foo_E)
					if dstValid := dstTypeOk || dst.FooOneof == nil || len(oneofSubs) == 0; !dstValid {
						return fmt.Errorf("attempt to set oneof 'e', while different oneof is set in destination")
					}
					if len(oneofSubs) > 0 {
						return fmt.Errorf("'e' has no subfields, but %s were specified", oneofSubs)
					}
					if srcTypeOk {
						dst.FooOneof = src.FooOneof
					} else {
						dst.FooOneof = nil
					}
				case "f":
					var srcTypeOk bool
					if src != nil {
						_, srcTypeOk = src.FooOneof.(*Foo_F)
					}
					if srcValid := srcTypeOk || src == nil || src.FooOneof == nil || len(oneofSubs) == 0; !srcValid {
						return fmt.Errorf("attempt to set oneof 'f', while different oneof is set in source")
					}
					_, dstTypeOk := dst.FooOneof.(*Foo_F)
					if dstValid := dstTypeOk || dst.FooOneof == nil || len(oneofSubs) == 0; !dstValid {
						return fmt.Errorf("attempt to set oneof 'f', while different oneof is set in destination")
					}
					if len(oneofSubs) > 0 {
						return fmt.Errorf("'f' has no subfields, but %s were specified", oneofSubs)
					}
					if srcTypeOk {
						dst.FooOneof = src.FooOneof
					} else {
						dst.FooOneof = nil
					}

				default:
					return fmt.Errorf("invalid oneof field: '%s.%s'", name, oneofName)
				}
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *Bar) SetFields(src *Bar, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "id":
			if len(subs) > 0 {
				return fmt.Errorf("'id' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Id = src.Id
			} else {
				var zero string
				dst.Id = zero
			}
		case "g":
			if len(subs) > 0 {
				return fmt.Errorf("'g' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.G = src.G
			} else {
				var zero int32
				dst.G = zero
			}
		case "created_at":
			if len(subs) > 0 {
				return fmt.Errorf("'created_at' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.CreatedAt = src.CreatedAt
			} else {
				dst.CreatedAt = nil
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *Foo_FooNested) SetFields(src *Foo_FooNested, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "id":
			if len(subs) > 0 {
				return fmt.Errorf("'id' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Id = src.Id
			} else {
				var zero string
				dst.Id = zero
			}
		case "b":
			if len(subs) > 0 {
				return fmt.Errorf("'b' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.B = src.B
			} else {
				var zero int32
				dst.B = zero
			}
		case "mappings":
			if len(subs) > 0 {
				return fmt.Errorf("'mappings' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Mappings = src.Mappings
			} else {
				dst.Mappings = nil
			}
		case "nested_nested":
			if len(subs) > 0 {
				var newDst, newSrc *Foo_FooNested_FooNestedNested
				if (src == nil || src.NestedNested == nil) && dst.NestedNested == nil {
					continue
				}
				if src != nil {
					newSrc = src.NestedNested
				}
				if dst.NestedNested != nil {
					newDst = dst.NestedNested
				} else {
					newDst = &Foo_FooNested_FooNestedNested{}
					dst.NestedNested = newDst
				}
				if err := newDst.SetFields(newSrc, subs...); err != nil {
					return err
				}
			} else {
				if src != nil {
					dst.NestedNested = src.NestedNested
				} else {
					dst.NestedNested = nil
				}
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *Foo_FooNested_FooNestedNested) SetFields(src *Foo_FooNested_FooNestedNested, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "id":
			if len(subs) > 0 {
				return fmt.Errorf("'id' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Id = src.Id
			} else {
				var zero string
				dst.Id = zero
			}
		case "c":
			if len(subs) > 0 {
				return fmt.Errorf("'c' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.C = src.C
			} else {
				var zero int32
				dst.C = zero
			}
		case "data":
			if len(subs) > 0 {
				return fmt.Errorf("'data' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.Data = src.Data
			} else {
				dst.Data = nil
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}
