// Copyright © 2022 The Things Network Foundation, The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: foo/foo.proto

package foo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	A  int32  `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	// Types that are assignable to FooOneof:
	//
	//	*Foo_D
	//	*Foo_E
	//	*Foo_F
	FooOneof  isFoo_FooOneof         `protobuf_oneof:"foo_oneof"`
	Nested    *Foo_FooNested         `protobuf:"bytes,6,opt,name=nested,proto3" json:"nested,omitempty"`
	Duration  *durationpb.Duration   `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Bars      []*Bar                 `protobuf:"bytes,9,rep,name=bars,proto3" json:"bars,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_foo_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_foo_foo_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (m *Foo) GetFooOneof() isFoo_FooOneof {
	if m != nil {
		return m.FooOneof
	}
	return nil
}

func (x *Foo) GetD() string {
	if x, ok := x.GetFooOneof().(*Foo_D); ok {
		return x.D
	}
	return ""
}

func (x *Foo) GetE() int32 {
	if x, ok := x.GetFooOneof().(*Foo_E); ok {
		return x.E
	}
	return 0
}

func (x *Foo) GetF() uint32 {
	if x, ok := x.GetFooOneof().(*Foo_F); ok {
		return x.F
	}
	return 0
}

func (x *Foo) GetNested() *Foo_FooNested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Foo) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Foo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Foo) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type isFoo_FooOneof interface {
	isFoo_FooOneof()
}

type Foo_D struct {
	D string `protobuf:"bytes,3,opt,name=d,proto3,oneof"`
}

type Foo_E struct {
	E int32 `protobuf:"varint,4,opt,name=e,proto3,oneof"`
}

type Foo_F struct {
	F uint32 `protobuf:"varint,5,opt,name=f,proto3,oneof"`
}

func (*Foo_D) isFoo_FooOneof() {}

func (*Foo_E) isFoo_FooOneof() {}

func (*Foo_F) isFoo_FooOneof() {}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	G         int32                  `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_foo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_foo_foo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_foo_foo_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bar) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Bar) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Foo_FooNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	B            int32                                     `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Mappings     map[string]*Foo_FooNested_FooNestedNested `protobuf:"bytes,3,rep,name=mappings,proto3" json:"mappings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NestedNested *Foo_FooNested_FooNestedNested            `protobuf:"bytes,4,opt,name=nested_nested,json=nestedNested,proto3" json:"nested_nested,omitempty"`
}

func (x *Foo_FooNested) Reset() {
	*x = Foo_FooNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_foo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo_FooNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo_FooNested) ProtoMessage() {}

func (x *Foo_FooNested) ProtoReflect() protoreflect.Message {
	mi := &file_foo_foo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo_FooNested.ProtoReflect.Descriptor instead.
func (*Foo_FooNested) Descriptor() ([]byte, []int) {
	return file_foo_foo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Foo_FooNested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo_FooNested) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Foo_FooNested) GetMappings() map[string]*Foo_FooNested_FooNestedNested {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *Foo_FooNested) GetNestedNested() *Foo_FooNested_FooNestedNested {
	if x != nil {
		return x.NestedNested
	}
	return nil
}

type Foo_FooNested_FooNestedNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	C    int32  `protobuf:"varint,2,opt,name=c,proto3" json:"c,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Foo_FooNested_FooNestedNested) Reset() {
	*x = Foo_FooNested_FooNestedNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_foo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo_FooNested_FooNestedNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo_FooNested_FooNestedNested) ProtoMessage() {}

func (x *Foo_FooNested_FooNestedNested) ProtoReflect() protoreflect.Message {
	mi := &file_foo_foo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo_FooNested_FooNestedNested.ProtoReflect.Descriptor instead.
func (*Foo_FooNested_FooNestedNested) Descriptor() ([]byte, []int) {
	return file_foo_foo_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Foo_FooNested_FooNestedNested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo_FooNested_FooNestedNested) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Foo_FooNested_FooNestedNested) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_foo_foo_proto protoreflect.FileDescriptor

var file_foo_foo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x66, 0x6f, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x04, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x12, 0x0e, 0x0a, 0x01, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x64, 0x12, 0x0e, 0x0a, 0x01, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x01, 0x65, 0x12, 0x0e, 0x0a, 0x01, 0x66,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x01, 0x66, 0x12, 0x2a, 0x0a, 0x06, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f,
	0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52,
	0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x72,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x42, 0x61,
	0x72, 0x52, 0x04, 0x62, 0x61, 0x72, 0x73, 0x1a, 0xd6, 0x02, 0x0a, 0x09, 0x46, 0x6f, 0x6f, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x62, 0x12, 0x3c, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x2e,
	0x46, 0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x47, 0x0a, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x46,
	0x6f, 0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x46, 0x6f, 0x6f,
	0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x0c, 0x6e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x1a, 0x5f, 0x0a, 0x0d, 0x4d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66,
	0x6f, 0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x2e, 0x46, 0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x2e, 0x46, 0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x43, 0x0a, 0x0f, 0x46,
	0x6f, 0x6f, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c,
	0x0a, 0x01, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x0b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x5e, 0x0a,
	0x03, 0x42, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x67, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x42, 0x5a,
	0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x65, 0x54,
	0x68, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x6d, 0x61, 0x73, 0x6b, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x66, 0x6f,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foo_foo_proto_rawDescOnce sync.Once
	file_foo_foo_proto_rawDescData = file_foo_foo_proto_rawDesc
)

func file_foo_foo_proto_rawDescGZIP() []byte {
	file_foo_foo_proto_rawDescOnce.Do(func() {
		file_foo_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_foo_foo_proto_rawDescData)
	})
	return file_foo_foo_proto_rawDescData
}

var file_foo_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_foo_foo_proto_goTypes = []interface{}{
	(*Foo)(nil),                           // 0: foo.Foo
	(*Bar)(nil),                           // 1: foo.Bar
	(*Foo_FooNested)(nil),                 // 2: foo.Foo.FooNested
	nil,                                   // 3: foo.Foo.FooNested.MappingsEntry
	(*Foo_FooNested_FooNestedNested)(nil), // 4: foo.Foo.FooNested.FooNestedNested
	(*durationpb.Duration)(nil),           // 5: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_foo_foo_proto_depIdxs = []int32{
	2, // 0: foo.Foo.nested:type_name -> foo.Foo.FooNested
	5, // 1: foo.Foo.duration:type_name -> google.protobuf.Duration
	6, // 2: foo.Foo.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: foo.Foo.bars:type_name -> foo.Bar
	6, // 4: foo.Bar.created_at:type_name -> google.protobuf.Timestamp
	3, // 5: foo.Foo.FooNested.mappings:type_name -> foo.Foo.FooNested.MappingsEntry
	4, // 6: foo.Foo.FooNested.nested_nested:type_name -> foo.Foo.FooNested.FooNestedNested
	4, // 7: foo.Foo.FooNested.MappingsEntry.value:type_name -> foo.Foo.FooNested.FooNestedNested
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_foo_foo_proto_init() }
func file_foo_foo_proto_init() {
	if File_foo_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foo_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foo_foo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foo_foo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo_FooNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foo_foo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo_FooNested_FooNestedNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_foo_foo_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Foo_D)(nil),
		(*Foo_E)(nil),
		(*Foo_F)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foo_foo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foo_foo_proto_goTypes,
		DependencyIndexes: file_foo_foo_proto_depIdxs,
		MessageInfos:      file_foo_foo_proto_msgTypes,
	}.Build()
	File_foo_foo_proto = out.File
	file_foo_foo_proto_rawDesc = nil
	file_foo_foo_proto_goTypes = nil
	file_foo_foo_proto_depIdxs = nil
}
