// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

var CreateFooRequestFieldPathsNested = []string{
	"foo",
	"foo.a",
	"foo.bars",
	"foo.created_at",
	"foo.duration",
	"foo.foo_oneof",
	"foo.foo_oneof.d",
	"foo.foo_oneof.e",
	"foo.foo_oneof.f",
	"foo.id",
	"foo.nested",
	"foo.nested.b",
	"foo.nested.id",
	"foo.nested.mappings",
	"foo.nested.nested_nested",
	"foo.nested.nested_nested.c",
	"foo.nested.nested_nested.data",
	"foo.nested.nested_nested.id",
}

var CreateFooRequestFieldPathsTopLevel = []string{
	"foo",
}

var GetFooRequestFieldPathsNested = []string{
	"field_mask",
	"foo_id",
}

var GetFooRequestFieldPathsTopLevel = []string{
	"field_mask",
	"foo_id",
}

var ListFooRequestFieldPathsNested = []string{
	"field_mask",
}

var ListFooRequestFieldPathsTopLevel = []string{
	"field_mask",
}

var ListFooResponseFieldPathsNested = []string{
	"foos",
}

var ListFooResponseFieldPathsTopLevel = []string{
	"foos",
}

var SetFooRequestFieldPathsNested = []string{
	"field_mask",
	"foo",
	"foo.a",
	"foo.bars",
	"foo.created_at",
	"foo.duration",
	"foo.foo_oneof",
	"foo.foo_oneof.d",
	"foo.foo_oneof.e",
	"foo.foo_oneof.f",
	"foo.id",
	"foo.nested",
	"foo.nested.b",
	"foo.nested.id",
	"foo.nested.mappings",
	"foo.nested.nested_nested",
	"foo.nested.nested_nested.c",
	"foo.nested.nested_nested.data",
	"foo.nested.nested_nested.id",
}

var SetFooRequestFieldPathsTopLevel = []string{
	"field_mask",
	"foo",
}
