// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

import fmt "fmt"

func (dst *CreateFooRequest) SetFields(src *CreateFooRequest, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "foo":
			if len(subs) > 0 {
				var newDst, newSrc *Foo
				if (src == nil || src.Foo == nil) && dst.Foo == nil {
					continue
				}
				if src != nil {
					newSrc = src.Foo
				}
				if dst.Foo != nil {
					newDst = dst.Foo
				} else {
					newDst = &Foo{}
					dst.Foo = newDst
				}
				if err := newDst.SetFields(newSrc, subs...); err != nil {
					return err
				}
			} else {
				if src != nil {
					dst.Foo = src.Foo
				} else {
					dst.Foo = nil
				}
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *GetFooRequest) SetFields(src *GetFooRequest, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "foo_id":
			if len(subs) > 0 {
				return fmt.Errorf("'foo_id' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.FooId = src.FooId
			} else {
				var zero string
				dst.FooId = zero
			}
		case "field_mask":
			if len(subs) > 0 {
				return fmt.Errorf("'field_mask' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.FieldMask = src.FieldMask
			} else {
				dst.FieldMask = nil
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *ListFooRequest) SetFields(src *ListFooRequest, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "field_mask":
			if len(subs) > 0 {
				return fmt.Errorf("'field_mask' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.FieldMask = src.FieldMask
			} else {
				dst.FieldMask = nil
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}

func (dst *SetFooRequest) SetFields(src *SetFooRequest, paths ...string) error {
	for name, subs := range _processPaths(paths) {
		switch name {
		case "foo":
			if len(subs) > 0 {
				var newDst, newSrc *Foo
				if (src == nil || src.Foo == nil) && dst.Foo == nil {
					continue
				}
				if src != nil {
					newSrc = src.Foo
				}
				if dst.Foo != nil {
					newDst = dst.Foo
				} else {
					newDst = &Foo{}
					dst.Foo = newDst
				}
				if err := newDst.SetFields(newSrc, subs...); err != nil {
					return err
				}
			} else {
				if src != nil {
					dst.Foo = src.Foo
				} else {
					dst.Foo = nil
				}
			}
		case "field_mask":
			if len(subs) > 0 {
				return fmt.Errorf("'field_mask' has no subfields, but %s were specified", subs)
			}
			if src != nil {
				dst.FieldMask = src.FieldMask
			} else {
				dst.FieldMask = nil
			}

		default:
			return fmt.Errorf("invalid field: '%s'", name)
		}
	}
	return nil
}
