// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package foo

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// ValidateFields checks the field values on CreateFooRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreateFooRequest) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = CreateFooRequestFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "foo":

			if v, ok := interface{}(m.GetFoo()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return CreateFooRequestValidationError{
						field:  "foo",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return CreateFooRequestValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// CreateFooRequestValidationError is the validation error returned by
// CreateFooRequest.ValidateFields if the designated constraints aren't met.
type CreateFooRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateFooRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateFooRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateFooRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateFooRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateFooRequestValidationError) ErrorName() string { return "CreateFooRequestValidationError" }

// Error satisfies the builtin error interface
func (e CreateFooRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateFooRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateFooRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateFooRequestValidationError{}

// ValidateFields checks the field values on GetFooRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetFooRequest) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = GetFooRequestFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "foo_id":
			// no validation rules for FooId
		case "field_mask":

			if v, ok := interface{}(m.GetFieldMask()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return GetFooRequestValidationError{
						field:  "field_mask",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return GetFooRequestValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// GetFooRequestValidationError is the validation error returned by
// GetFooRequest.ValidateFields if the designated constraints aren't met.
type GetFooRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFooRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFooRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFooRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFooRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFooRequestValidationError) ErrorName() string { return "GetFooRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetFooRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFooRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFooRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFooRequestValidationError{}

// ValidateFields checks the field values on ListFooRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListFooRequest) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = ListFooRequestFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "field_mask":

			if v, ok := interface{}(m.GetFieldMask()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return ListFooRequestValidationError{
						field:  "field_mask",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return ListFooRequestValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// ListFooRequestValidationError is the validation error returned by
// ListFooRequest.ValidateFields if the designated constraints aren't met.
type ListFooRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFooRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFooRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFooRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFooRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFooRequestValidationError) ErrorName() string { return "ListFooRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListFooRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFooRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFooRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFooRequestValidationError{}

// ValidateFields checks the field values on SetFooRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *SetFooRequest) ValidateFields(paths ...string) error {
	if m == nil {
		return nil
	}

	if len(paths) == 0 {
		paths = SetFooRequestFieldPathsNested
	}

	for name, subs := range _processPaths(append(paths[:0:0], paths...)) {
		_ = subs
		switch name {
		case "foo":

			if v, ok := interface{}(m.GetFoo()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return SetFooRequestValidationError{
						field:  "foo",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		case "field_mask":

			if v, ok := interface{}(m.GetFieldMask()).(interface{ ValidateFields(...string) error }); ok {
				if err := v.ValidateFields(subs...); err != nil {
					return SetFooRequestValidationError{
						field:  "field_mask",
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		default:
			return SetFooRequestValidationError{
				field:  name,
				reason: "invalid field path",
			}
		}
	}
	return nil
}

// SetFooRequestValidationError is the validation error returned by
// SetFooRequest.ValidateFields if the designated constraints aren't met.
type SetFooRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetFooRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetFooRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetFooRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetFooRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetFooRequestValidationError) ErrorName() string { return "SetFooRequestValidationError" }

// Error satisfies the builtin error interface
func (e SetFooRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetFooRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetFooRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetFooRequestValidationError{}
