// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package testdata

type RPCFieldMaskPathValue struct {
	All     []string
	Allowed []string
	Set     bool
}

// RPCFieldMaskPaths lists the field mask paths for each RPC in this API.
var RPCFieldMaskPaths = map[string]RPCFieldMaskPathValue{
	"/ttn.lorawan.v3.AsEndDeviceRegistry/Set": {
		All: TestFieldPathsNested,
		Allowed: []string{
			"a",
			"a.a",
			"b",
			"c",
			"testOneof",
			"g",
			"h",
			"i",
			"j",
			"l",
			"m",
		},
		Set: true,
	},
	"/ttn.lorawan.v3.AsEndDeviceRegistry/Get": {
		All: TestFieldPathsNested,
		Allowed: []string{
			"a",
			"a.a",
			"i",
			"j",
			"l",
			"m",
		},
		Set: false,
	},
}
