// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package testdata

var TestService2GetAllowedFieldMaskPaths = []string{
	"a",
	"a.a",
	"i",
	"j",
	"l",
	"m",
}

var TestServiceSetAllowedFieldMaskPaths = []string{
	"a",
	"a.a",
	"b",
	"c",
	"g",
	"h",
	"i",
	"j",
	"l",
	"m",
	"testOneof",
}
