// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package testdata

var EmptyFieldPathsNested []string
var EmptyFieldPathsTopLevel []string
var TestFieldPathsNested = []string{
	"a",
	"a.a",
	"a.a.a",
	"a.a.b",
	"a.a.c",
	"a.a.d",
	"a.a.h",
	"a.a.h.nested_field",
	"a.a.testNestedNestedOneOf",
	"a.a.testNestedNestedOneOf.e",
	"a.a.testNestedNestedOneOf.f",
	"a.a.testNestedNestedOneOf.g",
	"a.b",
	"a.c",
	"a.d",
	"a.e",
	"a.f",
	"b",
	"b.a",
	"b.a.a",
	"b.a.b",
	"b.a.c",
	"b.a.d",
	"b.a.h",
	"b.a.h.nested_field",
	"b.a.testNestedNestedOneOf",
	"b.a.testNestedNestedOneOf.e",
	"b.a.testNestedNestedOneOf.f",
	"b.a.testNestedNestedOneOf.g",
	"b.b",
	"b.c",
	"b.d",
	"b.e",
	"b.f",
	"c",
	"c.a",
	"c.a.a",
	"c.a.b",
	"c.a.c",
	"c.a.d",
	"c.a.h",
	"c.a.h.nested_field",
	"c.a.testNestedNestedOneOf",
	"c.a.testNestedNestedOneOf.e",
	"c.a.testNestedNestedOneOf.f",
	"c.a.testNestedNestedOneOf.g",
	"c.b",
	"c.c",
	"c.d",
	"c.e",
	"c.f",
	"g",
	"h",
	"i",
	"testOneof",
	"testOneof.d",
	"testOneof.e",
	"testOneof.f",
}

var TestFieldPathsTopLevel = []string{
	"a",
	"b",
	"c",
	"g",
	"h",
	"i",
	"testOneof",
}
var Test_TestNestedFieldPathsNested = []string{
	"a",
	"a.a",
	"a.b",
	"a.c",
	"a.d",
	"a.h",
	"a.h.nested_field",
	"a.testNestedNestedOneOf",
	"a.testNestedNestedOneOf.e",
	"a.testNestedNestedOneOf.f",
	"a.testNestedNestedOneOf.g",
	"b",
	"c",
	"d",
	"e",
	"f",
}

var Test_TestNestedFieldPathsTopLevel = []string{
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
}
var Test_TestNested_TestNestedNestedFieldPathsNested = []string{
	"a",
	"b",
	"c",
	"d",
	"h",
	"h.nested_field",
	"testNestedNestedOneOf",
	"testNestedNestedOneOf.e",
	"testNestedNestedOneOf.f",
	"testNestedNestedOneOf.g",
}

var Test_TestNested_TestNestedNestedFieldPathsTopLevel = []string{
	"a",
	"b",
	"c",
	"d",
	"h",
	"testNestedNestedOneOf",
}
var Test_TestNested_TestNestedNested_TestNestedNestedEmbedFieldPathsNested = []string{
	"nested_field",
}

var Test_TestNested_TestNestedNested_TestNestedNestedEmbedFieldPathsTopLevel = []string{
	"nested_field",
}
